# Generated by Django 4.0.4 on 2022-05-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epidemic',
            name='spread_type',
            field=models.CharField(choices=[('Airbone', 'A'), ('Waterbone', 'W'), ('Communicable', 'C')], default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='Genetic_Variation',
            field=models.CharField(choices=[('Mutations', 'M'), ('Recombinations', 'R'), ('Immigrations', 'I')], default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default=1, max_length=50),
        ),
    ]
